# This is a basic workflow to help you get started with Actions

name: Python application test with githun actions

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set-up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          make install
      - name: Lint with pylint
        run: make lint
      - name: test with pytest
        run: |
          make test
      
        

  
